template_update_delay=1
defaultEncoding=utf-8
url_escaping_charset=utf-8
locale=zh_CN
boolean_format=true,false
time_format=HH:mm:ss
date_format=yyyy-MM-dd
datetime_format=yyyy-MM-dd HH:mm:ss
number_format=0.######
classic_compatible=true
